"""update db 0.1

Revision ID: 12916a7decc0
Revises: 
Create Date: 2024-04-29 22:24:58.698584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12916a7decc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendaftar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('no_telp', sa.String(length=64), nullable=True),
    sa.Column('asal', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pendaftar')
    # ### end Alembic commands ###
